import Navbar from "@/components/navbar";
import BootstrapProvider from "@/providers/bootstrap-provider";
import { Inter } from "next/font/google";
import "../style.scss"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BootstrapProvider>
        <Navbar/>
          {children}
        </BootstrapProvider>
      </body>
    </html>
  );
}
